name: Python build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Install virtualenv
        run: |
          sudo apt update
          sudo apt install python3-pip
          python -m pip install virtualenv
      - name: Cache Python virtual environment
        id: pip-cache
        uses: actions/cache@v2
        with:
          path: ./scripts/venv
          key: ${{ runner.os }}-pip-cache-v4-${{ hashFiles('./scripts/requirements*.txt') }}

      - name: Install Python requirements
        if: steps.pip-cache.outputs.cache-hit != 'true'
        run: |
          virtualenv ./scripts/venv/
          source ./scripts/venv/bin/activate
          pip install -r ./scripts/requirements.txt -r ./scripts/requirements-code-style.txt

      - name: Run python static code analyzers
        run: |
          source ./scripts/venv/bin/activate
          flake8 ./scripts/ --count --statistics --config ./scripts/.flake8